version: "3"

services:
  redis:
    container_name: shortener-redis
    image: redis:alpine
    ports:
      - 6389:6379
    volumes:
      - shortener-redis-data:/shortener-redis-data
    restart: always

  mongo:
    container_name: shortener-mongodb
    image: mongo
    volumes:
      - shortener-mongo-data:/shortener-mongodb-data
    restart: always
    ports:
      - 27017:7071

volumes:
  shortener-redis-data:
  shortener-mongo-data:
